name: ClientConsole
main: dktapps\ClientConsole\Main
src-namespace-prefix: dktapps\ClientConsole
version: 0.2.0
api: [5.0.0]
load: POSTWORLD
author: dktapps
description: Relays console output to players as chat messages
website: https://github.com/dktapps/ClientConsole

permissions:
 clientconsole.receive:
  default: op
  description: Allows the permissible to receive output relayed from the console
