name: ClientConsole
main: dktapps\ClientConsole\Main
version: 0.0.1
api: 3.0.0-ALPHA7
load: POSTWORLD
author: dktapps
description: Relays console output to players as chat messages
website: https://github.com/dktapps/ClientConsole

permissions:
 clientconsole:
  default: op #child permissions don't get calculated correctly when op status changes
  description: ClientConsole root permission node
  children:
    clientconsole.receive:
     default: op
     description: Allows the permissible to receive output relayed from the console